defaults: &defaults
  adapter: mysql2
  encoding: utf8
  database: homeschool
  username: sehryan
  port: 3306
  host: 127.0.0.1
  socket: /tmp/mysql.so

development:
  password: regefab6
  <<: *defaults

production:
  host: localhost
  password: regefab6
  <<: *defaults
